name: Deploy to server

on:
  pull_request:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: root
          server: 185.241.55.239
          port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: ./*
          remote_path: /home/work_admin/web/vm4209002.43ssd.had.wf/public_html/fun
          args: '-o ConnectTimeout=5'
