name: Deploy to server

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      FILES_TO_COPY: ./*
      REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup key
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "$SSH_PRIVATE_KEY" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
      - name: Deploy
        run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete --exclude 'README.md' $FILES_TO_COPY $USERNAME@$SERVER_IP:$REMOTE_PATH
        working-directory: ./
